version: "3.4"
services:
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - '5672:5672'
      - '15672:15672'
  profile-service:
    build:
        dockerfile : /projects/ProfileService/Dockerfile
        context: .
    ports:
        - 9021:80
  ranking-service:
    build:
        dockerfile: /projects/DevRanker/DevRanker/Dockerfile
        context: .
    ports:
        - 9022:80 
    depends_on:
        - profile-service
  timeline-service:
    image: timelineservice
    build:
      context: .
      dockerfile: ./projects/TimelineService/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      rabbitmq:
        condition: service_healthy
  whitelist-service:
    user: "999"
    build:
      context: .
      dockerfile: projects/WhitelistService/Dockerfile
    container_name: 'whitelist-service'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '8080:8080'
